package app.model

import org.neo4j.ogm.annotation.Relationship

const val INCOMING = Relationship.INCOMING

const val PARTICIPANT_IN_COMPETITION = "PARTICIPANT_IN_COMPETITION"
const val MATCH_IN_COMPETITION = "MATCH_IN_COMPETITION"
const val CREATOR_OF_COMPETITION = "CREATOR_OF_COMPETITION"
const val ROUND_OF_STAGE = "ROUND_OF_STAGE"
const val STAGE_OF_COMPETITION = "STAGE_OF_COMPETITION"
const val EDITOR_OF_MATCH = "EDITOR_OF_MATCH"
const val PARTICIPANT_IN_MATCH = "PARTICIPANT_IN_MATCH"
const val MATCH_IN_ROUND = "MATCH_IN_ROUND"
const val IS_MATCH_PARTICIPANT = "IS_MATCH_PARTICIPANT"
const val IS_MATCH_TO_PROCEED_WITH = "IS_MATCH_TO_PROCEED_WITH"
const val FINAL_MATCH_OF_PLAYOFFS = "FINAL_MATCH_OF_CUP"
const val GROUP_OF_GROUP_STAGE = "GROUP_OF_GROUP_STAGE"
const val MATCH_IN_GROUP = "MATCH_IN_GROUP"
const val PARTICIPANT_IN_GROUP = "PARTICIPANT_IN_GROUP"
const val PLAYOFFS_QUOTE_FOR_GROUP = "PLAYOFFS_QUOTE_FOR_GROUP"
